"""
Shared Plotting Module — WS2 (Graphs From Scripts)

Every workstream emits its figures through this module so the entire project
uses a uniform style, dpi, path convention and footer stamp.

Output convention
-----------------
  results/figures/<workstream>/<name>.png
  (git-ignored generated artifact; regenerated by scripts; never hand-edited)

Helper
------
  figure_path(workstream, name) -> str
      Ensures the directory exists and returns the absolute path.

Figure functions (F1-F9 of the enumerated set)
-----------------------------------------------
  F1/F2/F3  plot_ms_heatmap(df, metric_col, workstream, name, **kw)
  F4         plot_growth_map(df, workstream, name, **kw)
  F5         plot_eds_overlay(a_sim, t_Gyr, t_start_Gyr, workstream, name, **kw)
  F6         plot_mu_z_panel(sim_dist, results, sim_params, workstream, name, **kw)
  F7         plot_shear_vs_lever(lever_values, shear_values, lever_label,
                                 workstream, name, **kw)
  F8         plot_dipole_vs_lever(lever_values, dipole_values, lever_label,
                                  workstream, name, **kw)
  F9         plot_runaway_boundary(df, workstream, name, **kw)

All functions return the path of the saved PNG.

WS1 caller contract (for the sweep tool / --plots-only mode)
-------------------------------------------------------------
  import pandas as pd
  from cosmo.plots import (figure_path, plot_ms_heatmap, plot_growth_map,
                            plot_runaway_boundary)

  df = pd.read_csv("results/sweep_results_pantheon.csv")
  plot_ms_heatmap(df, "chi2_dof",   "ws1", "ms_chi2_heatmap_vs_pantheon")
  plot_ms_heatmap(df, "chi2_lcdm",  "ws1", "ms_chi2_heatmap_vs_lcdm")
  plot_ms_heatmap(df, "chi2_eds",   "ws1", "ms_chi2_heatmap_vs_eds")
  plot_growth_map(df,               "ws1", "growth_map")
  plot_runaway_boundary(df,         "ws1", "runaway_boundary")

F5 caller contract (for the standalone EdS validation figure)
--------------------------------------------------------------
  from cosmo.plots import plot_eds_overlay
  plot_eds_overlay(a_sim, t_Gyr, t_start_Gyr=2.9,
                   workstream="ws2", name="eds_overlay_M0")

F6 caller contract (for the per-config mu(z)+residual panel)
-------------------------------------------------------------
  from cosmo.plots import plot_mu_z_panel
  plot_mu_z_panel(sim_dist, results, sim_params,
                  workstream="ws2", name=f"mu_z_panel_M{M}_S{S}")
  where sim_dist  = cosmo.sim_distance.sim_to_distance_modulus(...)
        results   = dict keyed by model name (same as hubble_diagram_nbody.run())

F7/F8 caller contract (for anisotropy_report.py)
-------------------------------------------------
  from cosmo.plots import plot_shear_vs_lever, plot_dipole_vs_lever
  plot_shear_vs_lever(amplitudes, shear_values, "node_mass_amplitude",
                      "ws2", "shear_vs_nma")
  plot_dipole_vs_lever(amplitudes, dipole_values, "node_mass_amplitude",
                       "ws2", "dipole_vs_nma")
"""

from __future__ import annotations

import os
import subprocess
import warnings
from typing import Optional, Sequence

import matplotlib
matplotlib.use("Agg")  # headless — must be before pyplot
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np

# ---------------------------------------------------------------------------
# Constants / defaults
# ---------------------------------------------------------------------------

_DPI = 150
_BBOX = "tight"
_RESULTS_ROOT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "results", "figures",
)

_MODEL_COLORS = {
    "external_node_nbody": "#ff7f0e",
    "lcdm":                "#1f77b4",
    "analytic_shortcut":   "#9467bd",
    "einstein_de_sitter":  "#2ca02c",
}
_MODEL_LABELS = {
    "external_node_nbody": "Ext-Node N-body",
    "lcdm":                "LCDM (analytic)",
    "analytic_shortcut":   "Analytic shortcut",
    "einstein_de_sitter":  "Matter-only / EdS (no Λ)",
}


# ---------------------------------------------------------------------------
# Path helper
# ---------------------------------------------------------------------------

def figure_path(workstream: str, name: str) -> str:
    """Return ``results/figures/<workstream>/<name>.png``, creating the dir.

    Args:
        workstream: Sub-directory label, e.g. ``"ws1"``, ``"ws2"``.
        name:       Descriptive filename stem (no extension, no spaces).

    Returns:
        Absolute path string ending in ``.png``.
    """
    directory = os.path.join(_RESULTS_ROOT, workstream)
    os.makedirs(directory, exist_ok=True)
    return os.path.join(directory, f"{name}.png")


# ---------------------------------------------------------------------------
# Footer helper
# ---------------------------------------------------------------------------

def _footer(ax: plt.Axes, config_str: str) -> None:
    """Stamp a tiny config + git-rev footer at the bottom of the axes."""
    try:
        rev = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=os.path.dirname(os.path.abspath(__file__)),
            stderr=subprocess.DEVNULL,
        ).decode().strip()
    except Exception:
        rev = "unknown"
    footer_text = f"rev {rev} | {config_str}"
    ax.annotate(
        footer_text,
        xy=(0.5, 0.0), xycoords="figure fraction",
        ha="center", va="bottom",
        fontsize=5, color="#888888",
        annotation_clip=False,
    )


# ---------------------------------------------------------------------------
# F1 / F2 / F3 — M-S chi2 heatmap
# ---------------------------------------------------------------------------

def plot_ms_heatmap(
    df,
    metric_col: str,
    workstream: str,
    name: str,
    *,
    title: Optional[str] = None,
    colorbar_label: Optional[str] = None,
    cmap: str = "viridis_r",
    mark_best: bool = True,
    best_is_min: bool = True,
    vmin: Optional[float] = None,
    vmax: Optional[float] = None,
) -> str:
    """Plot a 2-D M-S heatmap of a scalar metric from a sweep results DataFrame.

    Reads ``M_factor`` and ``S_gpc`` columns to form the grid axes; fills cells
    with ``metric_col``. Multiple rows for the same (M, S) are averaged. The
    best cell is marked with a white star when ``mark_best=True``.

    Args:
        df:             pandas DataFrame (or object with column access) containing
                        at minimum columns ``M_factor``, ``S_gpc``, and
                        ``metric_col``.
        metric_col:     Column name to colour the heatmap (e.g. ``"chi2_dof"``).
        workstream:     Sub-directory, e.g. ``"ws1"``.
        name:           PNG filename stem.
        title:          Figure title. Defaults to ``"M-S heatmap: <metric_col>"``.
        colorbar_label: Colorbar axis label. Defaults to ``metric_col``.
        cmap:           Matplotlib colormap name.
        mark_best:      Whether to mark the best cell with a star.
        best_is_min:    True => best = minimum (chi2); False => best = maximum.
        vmin / vmax:    Colormap range clipping.

    Returns:
        Path to the saved PNG.
    """
    import pandas as _pd

    df = _pd.DataFrame(df)  # accept dicts / DataFrames uniformly

    required = {"M_factor", "S_gpc", metric_col}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(
            f"plot_ms_heatmap: DataFrame is missing columns {sorted(missing)}. "
            f"Available: {sorted(df.columns)}"
        )

    # Pivot: average metric over duplicate (M, S) pairs
    pivot = (
        df[["M_factor", "S_gpc", metric_col]]
        .astype({metric_col: float})
        .groupby(["M_factor", "S_gpc"])[metric_col]
        .mean()
        .reset_index()
        .pivot(index="S_gpc", columns="M_factor", values=metric_col)
    )

    M_vals = pivot.columns.values.astype(float)
    S_vals = pivot.index.values.astype(float)
    Z = pivot.values  # shape (n_S, n_M)

    fig, ax = plt.subplots(figsize=(9, 6))

    img = ax.pcolormesh(
        M_vals, S_vals, Z,
        cmap=cmap, shading="nearest",
        vmin=vmin, vmax=vmax,
    )
    cbar = fig.colorbar(img, ax=ax)
    cbar.set_label(colorbar_label or metric_col, fontsize=11)

    ax.set_xlabel("M (node mass factor)", fontsize=12)
    ax.set_ylabel("S (node separation, Gpc)", fontsize=12)
    ax.set_title(title or f"M-S heatmap: {metric_col}", fontsize=13)

    # Mark best cell
    if mark_best:
        flat = Z.ravel()
        finite_mask = np.isfinite(flat)
        if np.any(finite_mask):
            finite_vals = flat.copy()
            finite_vals[~finite_mask] = np.inf if best_is_min else -np.inf
            best_flat = int(np.argmin(finite_vals) if best_is_min else np.argmax(finite_vals))
            bi, bj = np.unravel_index(best_flat, Z.shape)
            ax.plot(
                M_vals[bj], S_vals[bi],
                marker="*", color="white", ms=14, zorder=10,
                markeredgecolor="black", markeredgewidth=0.7,
                label=f"best {metric_col}={Z[bi, bj]:.3f}",
            )
            ax.legend(fontsize=9, loc="upper right")

    ax.set_xscale("log") if np.ptp(np.log10(M_vals[M_vals > 0])) > 1.5 else None

    _footer(ax, f"metric={metric_col}")
    fig.tight_layout()
    out = figure_path(workstream, name)
    fig.savefig(out, dpi=_DPI, bbox_inches=_BBOX)
    plt.close(fig)
    return out


# ---------------------------------------------------------------------------
# F4 — Growth-factor map
# ---------------------------------------------------------------------------

def plot_growth_map(
    df,
    workstream: str,
    name: str,
    *,
    growth_col: str = "growth_factor",
    anchor_col: Optional[str] = "anchor_ok",
    title: str = "Growth-factor map over (M, S)",
    target_growth: Optional[float] = None,
) -> str:
    """Plot the realized growth factor a(today)/a(t_start) over the (M, S) grid.

    Cells that fail the growth anchor (``anchor_ok == False``) are cross-hatched
    to visually distinguish bound vs runaway configs.

    Args:
        df:            Sweep results DataFrame.
        workstream:    Sub-directory.
        name:          PNG filename stem.
        growth_col:    Column name for the growth factor (default ``"growth_factor"``).
        anchor_col:    Column name for the boolean anchor flag (``None`` to skip).
        title:         Figure title.
        target_growth: Reference line value for the physical growth anchor.
                       If None the colorbar range auto-scales.

    Returns:
        Path to the saved PNG.
    """
    import pandas as _pd

    df = _pd.DataFrame(df)
    cols_needed = {"M_factor", "S_gpc", growth_col}
    missing = cols_needed - set(df.columns)
    if missing:
        raise ValueError(
            f"plot_growth_map: missing columns {sorted(missing)}."
        )

    pivot = (
        df[["M_factor", "S_gpc", growth_col]]
        .astype({growth_col: float})
        .groupby(["M_factor", "S_gpc"])[growth_col]
        .mean()
        .reset_index()
        .pivot(index="S_gpc", columns="M_factor", values=growth_col)
    )

    M_vals = pivot.columns.values.astype(float)
    S_vals = pivot.index.values.astype(float)
    Z = pivot.values

    fig, ax = plt.subplots(figsize=(9, 6))

    img = ax.pcolormesh(
        M_vals, S_vals, Z,
        cmap="RdYlGn", shading="nearest",
    )
    cbar = fig.colorbar(img, ax=ax)
    cbar.set_label("Growth factor a(today)/a(t_start)", fontsize=11)

    if target_growth is not None:
        cbar.ax.axhline(target_growth, color="blue", lw=1.5, ls="--")
        cbar.ax.annotate(
            f"target={target_growth:.2f}",
            xy=(1.05, target_growth),
            xycoords=("axes fraction", "data"),
            fontsize=7, color="blue",
        )

    # Cross-hatch cells that failed the anchor (runaway)
    if anchor_col is not None and anchor_col in df.columns:
        # Build a bool pivot (False = runaway = hatch)
        anchor_pivot = (
            df[["M_factor", "S_gpc", anchor_col]]
            .copy()
        )
        anchor_pivot["anchor_bool"] = anchor_pivot[anchor_col].map(
            lambda v: (str(v).strip().lower() not in ("false", "0", "no"))
        )
        anc = (
            anchor_pivot.groupby(["M_factor", "S_gpc"])["anchor_bool"]
            .min()
            .reset_index()
            .pivot(index="S_gpc", columns="M_factor", values="anchor_bool")
        )
        # Reindex to match pivot grid
        anc = anc.reindex(index=pivot.index, columns=pivot.columns)
        runaway = ~anc.values.astype(bool)
        for i in range(len(S_vals)):
            for j in range(len(M_vals)):
                if runaway[i, j]:
                    ax.add_patch(plt.Rectangle(
                        (M_vals[j] - 0.4, S_vals[i] - 0.4), 0.8, 0.8,
                        fill=False, hatch="///", edgecolor="red", lw=0.5, zorder=5,
                    ))

    ax.set_xlabel("M (node mass factor)", fontsize=12)
    ax.set_ylabel("S (node separation, Gpc)", fontsize=12)
    ax.set_title(title, fontsize=13)
    ax.set_xscale("log") if np.ptp(np.log10(M_vals[M_vals > 0])) > 1.5 else None

    _footer(ax, f"col={growth_col}")
    fig.tight_layout()
    out = figure_path(workstream, name)
    fig.savefig(out, dpi=_DPI, bbox_inches=_BBOX)
    plt.close(fig)
    return out


# ---------------------------------------------------------------------------
# F5 — M=0 == EdS overlay
# ---------------------------------------------------------------------------

def plot_eds_overlay(
    a_sim: np.ndarray,
    t_Gyr: np.ndarray,
    t_start_Gyr: float,
    workstream: str,
    name: str,
    *,
    title: str = "M=0 sim vs analytic EdS and ΛCDM",
    z_grid: Optional[np.ndarray] = None,
) -> str:
    """Plot the M=0 from-sim mu(z) alongside the analytic EdS and ΛCDM curves.

    This is the visual proof of PF1: with M=0 the sim reproduces EdS BY
    CONSTRUCTION, so the orange sim curve should sit ON the green EdS null
    and ~10x farther from the blue ΛCDM curve.

    Args:
        a_sim:        Scale-factor array from the simulation (a[0]=1 at t_start).
        t_Gyr:        Relative time array starting at 0, in Gyr (same length as a_sim).
        t_start_Gyr:  Absolute start time in Gyr (e.g. 2.9).
        workstream:   Sub-directory.
        name:         PNG filename stem.
        title:        Figure title.
        z_grid:       Optional redshift grid for analytic curves. Defaults to
                      linspace from sim z_max down to 0.01.

    Returns:
        Path to the saved PNG.
    """
    from .sim_distance import sim_to_distance_modulus
    from .distances import model_distance_modulus

    a_sim = np.asarray(a_sim, dtype=float)
    t_Gyr = np.asarray(t_Gyr, dtype=float)

    # Build a dense z grid spanning the sim's coverage
    if z_grid is None:
        t_abs = t_start_Gyr + t_Gyr
        t_today = 13.8
        a_norm = a_sim / a_sim[-1]
        z_snap = 1.0 / a_norm - 1.0
        z_max_sim = float(np.nanmax(z_snap[z_snap > 0.0]))
        z_grid = np.linspace(0.01, min(z_max_sim * 0.98, 2.3), 400)

    # --- from-sim mu(z) ---
    sd = sim_to_distance_modulus(z_grid, a_sim, t_Gyr, t_start_Gyr=t_start_Gyr)
    z_in = sd["z"]
    mu_sim_raw = sd["mu"]

    # --- analytic EdS and ΛCDM ---
    mu_eds  = model_distance_modulus(z_in, "einstein_de_sitter")
    mu_lcdm = model_distance_modulus(z_in, "lcdm")

    # Offset-marginalize each (using the sim offset)
    def _offset(mu_model, mu_obs):
        """Weighted mean offset — here we use uniform weights for simplicity
        since we only care about visual alignment."""
        return float(np.mean(mu_obs - mu_model))

    # Reference shift: align sim to EdS (they should be nearly identical)
    delta_sim  = _offset(mu_sim_raw,  mu_eds)
    delta_lcdm = _offset(mu_lcdm,     mu_eds)

    mu_sim_shifted  = mu_sim_raw  + delta_sim
    mu_lcdm_shifted = mu_lcdm    + delta_lcdm
    # EdS is the zero reference (no shift)

    fig, axes = plt.subplots(2, 1, figsize=(9, 8),
                             gridspec_kw={"height_ratios": [3, 1], "hspace": 0.08},
                             sharex=True)
    ax_top, ax_res = axes

    ax_top.plot(z_in, mu_sim_shifted, color=_MODEL_COLORS["external_node_nbody"],
                lw=2.5, label="M=0 N-body sim (should = EdS)")
    ax_top.plot(z_in, mu_eds, color=_MODEL_COLORS["einstein_de_sitter"],
                lw=2.0, ls="-.", label="Analytic EdS / matter-only (Ωm=1)")
    ax_top.plot(z_in, mu_lcdm_shifted, color=_MODEL_COLORS["lcdm"],
                lw=2.0, ls="--", label="Analytic ΛCDM (Ωm=0.3, ΩΛ=0.7)")

    ax_top.set_xscale("log")
    ax_top.set_ylabel("Distance modulus μ [mag]", fontsize=12)
    ax_top.set_title(title, fontsize=13)
    ax_top.legend(fontsize=9, loc="upper left")
    ax_top.grid(True, alpha=0.3, which="both")
    plt.setp(ax_top.get_xticklabels(), visible=False)

    # Residual panel: sim - EdS
    residual = mu_sim_shifted - mu_eds
    residual_lcdm = mu_lcdm_shifted - mu_eds
    ax_res.axhline(0.0, color=_MODEL_COLORS["einstein_de_sitter"], lw=1.5, ls="-.",
                   label="EdS (reference, 0)")
    ax_res.plot(z_in, residual, color=_MODEL_COLORS["external_node_nbody"],
                lw=2.0, label="sim − EdS (should ≈ 0)")
    ax_res.plot(z_in, residual_lcdm, color=_MODEL_COLORS["lcdm"],
                lw=1.5, ls="--", label="ΛCDM − EdS (should be large)")
    ax_res.set_xscale("log")
    ax_res.set_xlabel("Redshift z", fontsize=12)
    ax_res.set_ylabel("Δμ vs EdS [mag]", fontsize=10)
    ax_res.grid(True, alpha=0.3, which="both")
    ax_res.legend(fontsize=8, loc="upper right")

    max_dev = float(np.nanmax(np.abs(residual)))
    ax_top.text(
        0.02, 0.02,
        f"max|sim−EdS| = {max_dev:.3f} mag\n"
        f"(EdS-ΛCDM gap ≈ {float(np.nanmax(np.abs(residual_lcdm))):.2f} mag at z_max)",
        transform=ax_top.transAxes,
        fontsize=8, color="#333333",
        verticalalignment="bottom",
    )

    _footer(ax_res, f"t_start={t_start_Gyr} Gyr, M=0 EdS validation")
    out = figure_path(workstream, name)
    fig.savefig(out, dpi=_DPI, bbox_inches=_BBOX)
    plt.close(fig)
    return out


# ---------------------------------------------------------------------------
# F6 — Per-config mu(z) + Delta-mu panel
# ---------------------------------------------------------------------------

def plot_mu_z_panel(
    sim_dist: dict,
    results: dict,
    sim_params,
    workstream: str,
    name: str,
    *,
    data: Optional[dict] = None,
    in_range_mask: Optional[np.ndarray] = None,
    n_bins: int = 20,
) -> str:
    """Plot a two-panel Hubble diagram (mu(z) + Δμ vs ΛCDM residual).

    Mirrors the figure in hubble_diagram_nbody.py but callable directly from
    other scripts (sweep plots-only mode, anisotropy scripts, etc.).

    Args:
        sim_dist:     Output of ``cosmo.sim_distance.sim_to_distance_modulus``.
        results:      Dict keyed by model name, each value a dict with keys
                      ``chi2_dof``, ``R2``, ``DeltaM``, ``residuals`` — as
                      returned by ``cosmo.hubble_diagram.evaluate_precomputed /
                      evaluate_model``.
        sim_params:   ``SimulationParameters`` instance.
        workstream:   Sub-directory.
        name:         PNG filename stem.
        data:         Optional raw Pantheon data dict (keys: z, mu, sigma, n).
                      When supplied the scatter data is overlaid.
        in_range_mask: Boolean mask aligned to ``data["z"]`` marking in-range SNe.
        n_bins:       Number of log-z bins for the binned overlay.

    Returns:
        Path to the saved PNG.
    """
    from .distances import model_distance_modulus

    z_in   = sim_dist["z"]
    mu_sim = sim_dist["mu"]
    z_cover = sim_dist["z_cover"]

    # Build a dense z grid for smooth curves
    z_dense = np.linspace(max(z_cover[0] + 1e-4, 0.011), z_cover[1] - 1e-4, 400)

    mu_sim_dense  = np.interp(z_dense, z_in, mu_sim)
    mu_lcdm_dense = model_distance_modulus(z_dense, "lcdm")
    mu_eds_dense  = model_distance_modulus(z_dense, "einstein_de_sitter")

    r_sim  = results.get("external_node_nbody", {})
    r_lcdm = results.get("lcdm", {})
    r_eds  = results.get("einstein_de_sitter", {})

    deltaM_sim  = float(r_sim.get("DeltaM", 0.0))
    deltaM_lcdm = float(r_lcdm.get("DeltaM", 0.0))
    deltaM_eds  = float(r_eds.get("DeltaM", 0.0))

    mu_sim_shifted  = mu_sim_dense  + deltaM_sim
    mu_lcdm_shifted = mu_lcdm_dense + deltaM_lcdm
    mu_eds_shifted  = mu_eds_dense  + deltaM_eds

    fig, axes = plt.subplots(2, 1, figsize=(11, 8),
                             gridspec_kw={"height_ratios": [3, 1], "hspace": 0.08},
                             sharex=True)
    ax_top, ax_res = axes

    # Pantheon scatter
    if data is not None and in_range_mask is not None:
        from cosmo import pantheon as _pantheon
        z_data  = data["z"]
        mu_data = data["mu"]
        sg_data = data["sigma"]
        z_plot  = z_data[in_range_mask]
        mu_plot = mu_data[in_range_mask]
        sg_plot = sg_data[in_range_mask]
        ax_top.scatter(z_data, mu_data, s=1.5, alpha=0.07, color="gray",
                       rasterized=True, label="_nolegend_")
        ax_top.scatter(z_plot, mu_plot, s=2.0, alpha=0.18, color="#555555",
                       rasterized=True, label="_nolegend_")
        binned = _pantheon.bin_for_plot(z_plot, mu_plot, sg_plot, n_bins=n_bins)
        ax_top.errorbar(binned["z"], binned["mu"], yerr=binned["err"],
                        fmt="o", color="black", ms=4, lw=1.2, capsize=2.5, zorder=3,
                        label=f"Pantheon+SH0ES ({len(z_plot)} SNe in range)")

    # Model curves
    ax_top.plot(z_dense, mu_sim_shifted,
                color=_MODEL_COLORS["external_node_nbody"], lw=2.5,
                label=(f"Ext-Node N-body  χ²/dof={r_sim.get('chi2_dof', float('nan')):.3f}"
                       f"  R²={r_sim.get('R2', float('nan')):.4f}"))
    ax_top.plot(z_dense, mu_lcdm_shifted,
                color=_MODEL_COLORS["lcdm"], lw=2.0, ls="--",
                label=(f"ΛCDM  χ²/dof={r_lcdm.get('chi2_dof', float('nan')):.3f}"
                       f"  R²={r_lcdm.get('R2', float('nan')):.4f}"))
    ax_top.plot(z_dense, mu_eds_shifted,
                color=_MODEL_COLORS["einstein_de_sitter"], lw=1.8, ls="-.",
                label=(f"EdS null  χ²/dof={r_eds.get('chi2_dof', float('nan')):.3f}"))

    for zv in z_cover:
        ax_top.axvline(zv, color="gray", ls=":", lw=0.8, alpha=0.7)

    ax_top.set_xscale("log")
    ax_top.set_ylabel("Distance modulus μ [mag]", fontsize=12)
    M = getattr(sim_params, "M_value", "?")
    S = getattr(sim_params, "S_value", "?")
    ax_top.set_title(
        f"Hubble Diagram — N-body a(t) vs Pantheon+SH0ES\n"
        f"M={M}, S={S},  sim z-range [{z_cover[0]:.3f}, {z_cover[1]:.3f}]",
        fontsize=11,
    )
    ax_top.legend(fontsize=8.5, loc="upper left")
    ax_top.grid(True, alpha=0.3, which="both")
    plt.setp(ax_top.get_xticklabels(), visible=False)

    # Residual panel (Δμ vs ΛCDM)
    ax_res.axhline(0.0, color=_MODEL_COLORS["lcdm"], lw=1.5, ls="--",
                   label="ΛCDM (Δμ = 0 reference)")
    ax_res.plot(z_dense, mu_sim_shifted - mu_lcdm_shifted,
                color=_MODEL_COLORS["external_node_nbody"], lw=2.0,
                label="Ext-Node − ΛCDM")
    ax_res.plot(z_dense, mu_eds_shifted - mu_lcdm_shifted,
                color=_MODEL_COLORS["einstein_de_sitter"], lw=1.5, ls="-.",
                label="EdS − ΛCDM")

    # Per-SN residuals (scatter)
    if r_sim.get("residuals") is not None and data is not None and in_range_mask is not None:
        ax_res.scatter(z_plot, np.asarray(r_sim["residuals"]),
                       s=1.5, alpha=0.15, color=_MODEL_COLORS["external_node_nbody"],
                       rasterized=True)

    ax_res.set_xscale("log")
    ax_res.set_xlabel("Redshift z", fontsize=12)
    ax_res.set_ylabel("Δμ vs ΛCDM [mag]", fontsize=10)
    ax_res.set_ylim(-1.5, 1.5)
    ax_res.grid(True, alpha=0.3, which="both")
    ax_res.legend(fontsize=8, loc="upper right")

    _footer(ax_res, f"M={M} S={S}")
    out = figure_path(workstream, name)
    fig.savefig(out, dpi=_DPI, bbox_inches=_BBOX)
    plt.close(fig)
    return out


# ---------------------------------------------------------------------------
# F7 — Shear index vs lever value
# ---------------------------------------------------------------------------

def plot_shear_vs_lever(
    lever_values: Sequence[float],
    shear_values: Sequence[float],
    lever_label: str,
    workstream: str,
    name: str,
    *,
    title: Optional[str] = None,
    color: str = "#e377c2",
) -> str:
    """Scatter + line plot of shear_index vs a single symmetry-breaking lever.

    Args:
        lever_values:  1-D sequence of lever parameter values.
        shear_values:  1-D sequence of shear_index values (same length).
        lever_label:   X-axis label, e.g. ``"node_mass_amplitude"``.
        workstream:    Sub-directory.
        name:          PNG filename stem.
        title:         Figure title.
        color:         Line / marker color.

    Returns:
        Path to the saved PNG.
    """
    x = np.asarray(lever_values, dtype=float)
    y = np.asarray(shear_values, dtype=float)

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(x, y, "o-", color=color, lw=1.8, ms=6)
    ax.set_xlabel(lever_label, fontsize=12)
    ax.set_ylabel("Shear index (λ_max − λ_min) / mean(λ)", fontsize=11)
    ax.set_title(title or f"Shear anisotropy vs {lever_label}", fontsize=13)
    ax.grid(True, alpha=0.3)

    _footer(ax, f"lever={lever_label}")
    fig.tight_layout()
    out = figure_path(workstream, name)
    fig.savefig(out, dpi=_DPI, bbox_inches=_BBOX)
    plt.close(fig)
    return out


# ---------------------------------------------------------------------------
# F8 — Hubble dipole vs lever value
# ---------------------------------------------------------------------------

def plot_dipole_vs_lever(
    lever_values: Sequence[float],
    dipole_values: Sequence[float],
    lever_label: str,
    workstream: str,
    name: str,
    *,
    title: Optional[str] = None,
    color: str = "#d62728",
) -> str:
    """Scatter + line plot of Hubble dipole ΔH/H vs a symmetry-breaking lever.

    Args:
        lever_values:   1-D sequence of lever parameter values.
        dipole_values:  1-D sequence of dipole (ΔH/H) values.
        lever_label:    X-axis label, e.g. ``"node_mass_amplitude"``.
        workstream:     Sub-directory.
        name:           PNG filename stem.
        title:          Figure title.
        color:          Line / marker color.

    Returns:
        Path to the saved PNG.
    """
    x = np.asarray(lever_values, dtype=float)
    y = np.asarray(dipole_values, dtype=float)

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(x, y, "s-", color=color, lw=1.8, ms=6)
    ax.set_xlabel(lever_label, fontsize=12)
    ax.set_ylabel("Hubble dipole ΔH/H (dimensionless)", fontsize=11)
    ax.set_title(title or f"Hubble dipole vs {lever_label}", fontsize=13)
    ax.grid(True, alpha=0.3)

    _footer(ax, f"lever={lever_label}")
    fig.tight_layout()
    out = figure_path(workstream, name)
    fig.savefig(out, dpi=_DPI, bbox_inches=_BBOX)
    plt.close(fig)
    return out


# ---------------------------------------------------------------------------
# F9 — Runaway-boundary map
# ---------------------------------------------------------------------------

def plot_runaway_boundary(
    df,
    workstream: str,
    name: str,
    *,
    anchor_col: str = "anchor_ok",
    title: str = "Runaway boundary in (M, S) — red = runaway, green = bound",
) -> str:
    """Binary (bound / runaway) map over the (M, S) grid from a sweep CSV.

    Each cell is coloured green (anchor_ok=True, bound) or red (runaway). The
    S_crit ∝ M^(1/3) scaling is drawn as an annotation guide.

    Args:
        df:          Sweep results DataFrame.
        workstream:  Sub-directory.
        name:        PNG filename stem.
        anchor_col:  Boolean column marking physical configs (default ``"anchor_ok"``).
        title:       Figure title.

    Returns:
        Path to the saved PNG.
    """
    import pandas as _pd

    df = _pd.DataFrame(df)
    required = {"M_factor", "S_gpc", anchor_col}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"plot_runaway_boundary: missing columns {sorted(missing)}.")

    df2 = df[["M_factor", "S_gpc", anchor_col]].copy()
    df2["anchor_bool"] = df2[anchor_col].map(
        lambda v: (str(v).strip().lower() not in ("false", "0", "no"))
    ).astype(int)

    pivot = (
        df2.groupby(["M_factor", "S_gpc"])["anchor_bool"]
        .mean()
        .reset_index()
        .pivot(index="S_gpc", columns="M_factor", values="anchor_bool")
    )

    M_vals = pivot.columns.values.astype(float)
    S_vals = pivot.index.values.astype(float)
    Z = pivot.values   # values in [0, 1] — fraction of runs that are bound

    fig, ax = plt.subplots(figsize=(9, 6))
    cmap_rb = mcolors.ListedColormap(["#d62728", "#2ca02c"])
    img = ax.pcolormesh(
        M_vals, S_vals, Z,
        cmap=cmap_rb, shading="nearest", vmin=0, vmax=1,
    )
    cbar = fig.colorbar(img, ax=ax, ticks=[0.25, 0.75])
    cbar.ax.set_yticklabels(["runaway", "bound"])

    # S_crit ~ M^(1/3) guide line
    if len(M_vals) > 1:
        M_range = np.linspace(M_vals.min(), M_vals.max(), 200)
        # Fit S_crit for each M using the boundary (cells that transition 0->1)
        # Simplified: draw reference line anchored at median M
        m_mid = M_vals[len(M_vals) // 2]
        # Find the lowest S that is bound at m_mid (if available)
        try:
            col_idx = int(np.argmin(np.abs(M_vals - m_mid)))
            col_vals = Z[:, col_idx]
            bound_rows = np.where(col_vals > 0.5)[0]
            if len(bound_rows):
                s_ref = S_vals[bound_rows[0]]
                s_guide = s_ref * (M_range / m_mid) ** (1.0 / 3.0)
                ax.plot(M_range, s_guide, "k--", lw=1.5, alpha=0.6,
                        label=r"$S_{\rm crit} \propto M^{1/3}$ guide")
                ax.legend(fontsize=9)
        except Exception:
            pass

    ax.set_xlabel("M (node mass factor)", fontsize=12)
    ax.set_ylabel("S (node separation, Gpc)", fontsize=12)
    ax.set_title(title, fontsize=12)
    try:
        if np.ptp(np.log10(M_vals[M_vals > 0])) > 1.5:
            ax.set_xscale("log")
    except Exception:
        pass

    _footer(ax, f"anchor={anchor_col}")
    fig.tight_layout()
    out = figure_path(workstream, name)
    fig.savefig(out, dpi=_DPI, bbox_inches=_BBOX)
    plt.close(fig)
    return out


# ---------------------------------------------------------------------------
# Convenience: regenerate all heatmaps from a CSV (--plots-only mode)
# ---------------------------------------------------------------------------

def plots_from_csv(
    csv_path: str,
    workstream: str = "ws1",
    *,
    metrics: Optional[list] = None,
) -> list[str]:
    """Regenerate all standard heatmap figures from a sweep results CSV.

    This is the core of the ``--plots-only <csv>`` mode in WS1.  It reads
    the CSV, then emits F1, F2 (if cols present), F4, and F9.

    Args:
        csv_path:    Path to the sweep CSV.
        workstream:  Sub-directory for the output figures.
        metrics:     List of metric column names to heatmap. Defaults to
                     ``["chi2_dof", "chi2_lcdm", "growth_factor"]``.

    Returns:
        List of saved PNG paths.
    """
    import pandas as _pd

    df = _pd.read_csv(csv_path)
    if metrics is None:
        metrics = []
        for col in ("chi2_dof", "chi2_lcdm", "chi2_eds"):
            if col in df.columns:
                metrics.append(col)
        if not metrics and "chi2_dof" in df.columns:
            metrics = ["chi2_dof"]

    out_paths: list[str] = []

    for m in metrics:
        if m not in df.columns:
            warnings.warn(f"plots_from_csv: column {m!r} not in CSV, skipping.")
            continue
        best_is_min = "chi2" in m or "rmse" in m or "diff" in m
        out_paths.append(plot_ms_heatmap(
            df, m, workstream,
            name=f"ms_{m}_heatmap",
            best_is_min=best_is_min,
        ))

    if "growth_factor" in df.columns:
        out_paths.append(plot_growth_map(
            df, workstream, "growth_map",
        ))

    if "anchor_ok" in df.columns:
        out_paths.append(plot_runaway_boundary(
            df, workstream, "runaway_boundary",
        ))

    return out_paths
